### ISSUE TITLE
Video crash when in fullscreen

### ISSUE THREAD

**Issue by mrigo** [LonnyGomes/vjs-video#54]
Hi,
I've this code

```
angular
  .module('hrassistantApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ui.router',
    'gettext',
    'LocalStorageModule',
    'ui.bootstrap',
    'slickCarousel',
    'angular-jwt',
    'angularModalService',
    'ngRetina',
    'truncate',
    'ng.deviceDetector',
    'angular-fallback-image',
    'vjs.video'
  ]);

in html

<video class="video-js vjs-default-skin" controls preload="auto"
                width="640" height="264" poster="poster.jpg" vjs-video>
                <source src="https://videourl/Main_video.mp4" type="video/mp4">
            </video>

```

The video starts without problem, but when I try to go fullscreen by clicking the fullscreen control button, I've this error:
```

video.js:21347 VIDEOJS: ERROR: TypeError: Cannot read property 'vdata1481645318439' of null
    at Object.hasElData (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:20077:14)
    at Object.trigger (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:21034:22)
    at Player.trigger (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:1771:12)
    at Player.documentFullscreenChange (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:10191:17)
    at HTMLDocument.bound (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:21135:15)
    at HTMLDocument.data.dispatcher (http://0.0.0.0:9000/bower_components/video.js/dist/video.js:20926:31)logByType @ video.js:21347
http://0.0.0.0:9000/poster.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
```
<img width="1132" alt="schermata 2016-12-13 alle 17 14 54" src="https://cloud.githubusercontent.com/assets/2822656/21148205/c4d3785c-c157-11e6-88dd-86b5960d100b.png">

I'm on localhost with grunt.

What can I do?

Thanks
\m

**Comment by mrigo** [comment]
Sorry, my fault, I must reload the page when the window's width change.
So I can see the video in fullscreen but then the page reloaded.
Thanks for the great library!
