### ISSUE TITLE
hi~

### ISSUE THREAD

**Issue by Shangxq** [LonnyGomes/vjs-video#68]
videojs v4.12.15
When I use the rtmp protocol to play video, and then switch to other video when the error, but it seems to have no effect.
error info:
VIDEOJS: Video.js: currentTime unavailable on Flash playback technology element. TypeError: this.el_.vjs_getProperty is not a function
    at subObj.api.(anonymous function) [as seeking] (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:7996:45)
    at subObj.vjs.Flash.currentTime (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:7927:12)
    at subObj.vjs.Player.techGet (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:4322:31)
    at subObj.vjs.Player.currentTime (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:4407:42)
    at subObj.vjs.CurrentTimeDisplay.updateContent (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:5602:92)
    at subObj.ret (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:885:15)
    at HTMLDivElement.ret (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:885:15)
    at HTMLDivElement.data.dispatcher (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:360:29)
    at Function.vjs.trigger (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:605:25)
    at subObj.vjs.Component.trigger (http://localhost:63342/vjs/bower_components/video.js/dist/video-js/video.dev.js:2503:7)

**Comment by ghost** [comment]
Do you have a code sample I could take a look at?

**Comment by Shangxq** [comment]
_**# html:**_
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="amazeui.videojs.css" />
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/video.dev.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/vjs-video/dist/vjs-video.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/lang/zh-CN.js"></script>
    <script src="vjs-plugins.js"></script>
</head>
<body ng-controller="MainCtrl">
<video id="course-video" class="video-js vjs-amazeui" controls width="640" height="268"
       preload="auto"
       vjs-setup='option' vjs-video vjs-media="media">
</video>
<button data-ng-click="toggleMedia()">NEXT</button>
<span data-ng-bind="currentImg"></span>
<script src="main.js"></script>
</body>
</html>
 _**js:#**_
angular.module('app', ['vjs.video']).controller("MainCtrl", ["$scope", function ($scope) {
    $scope.option = {
        language: 'zh-CN',
        plugins: {
            BackBtn: {},
            NextBtn: {}
        },
        children: {
            textTrackDisplay: false,
            posterImage: false,
            errorDisplay: false,
            controlBar: {
                captionsButton: false,
                chaptersButton: false,
                subtitlesButton: false,
                liveDisplay: false,
                playbackRateMenuButton: false
            }
        }
    };
    $scope.currentImg = 'first';
    $scope.chapterVideoPics = [
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 1,
            "nextVedioTime": 20,
            "picId": 'pic1',
            "previousVedioTime": 0,
            "vedioTime": 0
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 2,
            "nextVedioTime": 40,
            "picId": 'pic2',
            "previousVedioTime": 0,
            "vedioTime": 20
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 3,
            "nextVedioTime": 60,
            "picId": 'pic3',
            "previousVedioTime": 20,
            "vedioTime": 40
        }
    ];
    $scope.$on('vjsVideoReady', function (evt, videoData) {
        $scope.videoPlayer = videoData.vid;
        $scope.videoPlayer.on('timeupdate', function () {
            if (!$scope.$$phase) {
                $scope.$apply(function () {
                    $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
                })
            } else {
                $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
            }
        })
    });
    $scope.checkImg = function (VideoPics, currenttime) {
        var picId = '';
        for (var i in VideoPics) {
            if (VideoPics[i].vedioTime < currenttime && VideoPics[i].nextVedioTime > currenttime) {
                picId = VideoPics[i].picId;
                break;
            }
        }
        if (picId === '') {
            picId = VideoPics[VideoPics.length - 1].picId;
        }
        return picId;
    };
    $scope.media = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_300.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };

    $scope.toggleMedia = function () {
        $scope.media = $scope.semedia;

    };
    $scope.semedia = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_3001.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };
    $scope.seekTime = function (time) {
        $scope.videoPlayer.currentTime(time);
    };
}]);

**Comment by Shangxq** [comment]
**_html_**
`<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="amazeui.videojs.css" />
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/video.dev.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/vjs-video/dist/vjs-video.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/lang/zh-CN.js"></script>
    <script src="vjs-plugins.js"></script>
</head>
<body ng-controller="MainCtrl">
<video id="course-video" class="video-js vjs-amazeui" controls width="640" height="268"
       preload="auto"
       vjs-setup='option' vjs-video vjs-media="media">
</video>
<button data-ng-click="toggleMedia()">下一个</button>
<span data-ng-bind="currentImg"></span>
<script src="main.js"></script>
</body>
</html>`

**Comment by Shangxq** [comment]
**_html_**
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="amazeui.videojs.css" />
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/video.dev.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/vjs-video/dist/vjs-video.min.js"></script>
    <script src="bower_components/video.js/dist/video-js/lang/zh-CN.js"></script>
    <script src="vjs-plugins.js"></script>
</head>
<body ng-controller="MainCtrl">
<video id="course-video" class="video-js vjs-amazeui" controls width="640" height="268"
       preload="auto"
       vjs-setup='option' vjs-video vjs-media="media">
</video>
<button data-ng-click="toggleMedia()">NEXT</button>
<span data-ng-bind="currentImg"></span>
<script src="main.js"></script>
</body>
</html>

**Comment by Shangxq** [comment]
**_js_**
`angular.module('app', ['vjs.video']).controller("MainCtrl", ["$scope", function ($scope) {
    $scope.option = {
        language: 'zh-CN',
        plugins: {
            BackBtn: {},
            NextBtn: {}
        },
        children: {
            textTrackDisplay: false,
            posterImage: false,
            errorDisplay: false,
            controlBar: {
                captionsButton: false,
                chaptersButton: false,
                subtitlesButton: false,
                liveDisplay: false,
                playbackRateMenuButton: false
            }
        }
    };
    $scope.currentImg = 'first';
    $scope.chapterVideoPics = [
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 1,
            "nextVedioTime": 20,
            "picId": 'pic1',
            "previousVedioTime": 0,
            "vedioTime": 0
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 2,
            "nextVedioTime": 40,
            "picId": 'pic2',
            "previousVedioTime": 0,
            "vedioTime": 20
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 3,
            "nextVedioTime": 60,
            "picId": 'pic3',
            "previousVedioTime": 20,
            "vedioTime": 40
        }
    ];
    $scope.$on('vjsVideoReady', function (evt, videoData) {
        $scope.videoPlayer = videoData.vid;
        $scope.videoPlayer.on('timeupdate', function () {
            if (!$scope.$$phase) {
                $scope.$apply(function () {
                    $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
                })
            } else {
                $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
            }
        })
    });
    $scope.checkImg = function (VideoPics, currenttime) {
        var picId = '';
        for (var i in VideoPics) {
            if (VideoPics[i].vedioTime < currenttime && VideoPics[i].nextVedioTime > currenttime) {
                picId = VideoPics[i].picId;
                break;
            }
        }
        if (picId === '') {
            picId = VideoPics[VideoPics.length - 1].picId;
        }
        return picId;
    };
    $scope.media = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_300.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };

    $scope.toggleMedia = function () {
        $scope.media = $scope.semedia;

    };
    $scope.semedia = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_3001.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };
    $scope.seekTime = function (time) {
        $scope.videoPlayer.currentTime(time);
    };
}]);`

**Comment by Shangxq** [comment]
**_js_**
angular.module('app', ['vjs.video']).controller("MainCtrl", ["$scope", function ($scope) {
    $scope.option = {
        language: 'zh-CN',
        plugins: {
            BackBtn: {},
            NextBtn: {}
        },
        children: {
            textTrackDisplay: false,
            posterImage: false,
            errorDisplay: false,
            controlBar: {
                captionsButton: false,
                chaptersButton: false,
                subtitlesButton: false,
                liveDisplay: false,
                playbackRateMenuButton: false
            }
        }
    };
    $scope.currentImg = 'first';
    $scope.chapterVideoPics = [
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 1,
            "nextVedioTime": 20,
            "picId": 'pic1',
            "previousVedioTime": 0,
            "vedioTime": 0
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 2,
            "nextVedioTime": 40,
            "picId": 'pic2',
            "previousVedioTime": 0,
            "vedioTime": 20
        },
        {
            "courseChapterId": 0,
            "courseChapterName": "string",
            "id": 3,
            "nextVedioTime": 60,
            "picId": 'pic3',
            "previousVedioTime": 20,
            "vedioTime": 40
        }
    ];
    $scope.$on('vjsVideoReady', function (evt, videoData) {
        $scope.videoPlayer = videoData.vid;
        $scope.videoPlayer.on('timeupdate', function () {
            if (!$scope.$$phase) {
                $scope.$apply(function () {
                    $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
                })
            } else {
                $scope.currentImg = $scope.checkImg($scope.chapterVideoPics, $scope.videoPlayer.currentTime());
            }
        })
    });
    $scope.checkImg = function (VideoPics, currenttime) {
        var picId = '';
        for (var i in VideoPics) {
            if (VideoPics[i].vedioTime < currenttime && VideoPics[i].nextVedioTime > currenttime) {
                picId = VideoPics[i].picId;
                break;
            }
        }
        if (picId === '') {
            picId = VideoPics[VideoPics.length - 1].picId;
        }
        return picId;
    };
    $scope.media = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_300.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };

    $scope.toggleMedia = function () {
        $scope.media = $scope.semedia;

    };
    $scope.semedia = {
        sources: [
            {
                src: 'rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_3001.mp4',
                type: 'rtmp/mp4'
            }
        ]
    };
    $scope.seekTime = function (time) {
        $scope.videoPlayer.currentTime(time);
    };
}]);

**Comment by Shangxq** [comment]
when click NEXT button

**Comment by ghost** [comment]
Hello @Shangxq, were you ever able to resolve your problem?

**Comment by Shangxq** [comment]
I'm so sorry to reply to you so late，I switched to becoming an Java Engineer.I have no time to solve such a problem before.You are very friendly and hope to have the opportunity to communicate with you.(My English is poor, and the above comes from Google translation   ：） ）
